### ISSUE TITLE
论文问题

### ISSUE THREAD

**Issue by Upcreat** [iMoonLab/Hyper-YOLO#1]
您好，感谢您的项目。论文是否还没发表，暂时没有搜到。

**Comment by yifanfeng97** [comment]
感谢您的关注，我们的论文已经提交到arxiv，很快就会被检索到。我先给您放一个云盘的临时链接：https://cloud.tsinghua.edu.cn/f/c2ec5c0db163493bb45c/

**Comment by Upcreat** [comment]
感谢您的回复。谢谢您的分享~
