### ISSUE TITLE
instances_val2017.json file not found

### ISSUE THREAD

**Issue by DL-Mao** [iMoonLab/Hyper-YOLO#3]
hi, I got an issue about ### _pycocotools unable to run: F:\Hyper-YOLO-main\datasets\coco\annotations\instances_val2017.json file not found_. If you have ever encountered such a problem, I would greatly appreciate it if you could provide a solution.
![1](https://github.com/user-attachments/assets/28ee3b68-80bb-4503-bea9-8d087b2852e7)
but But in my datasets folder, the instances_val2017.json file does exist.
![2](https://github.com/user-attachments/assets/6cd8dd42-53b0-4940-845c-29283eac63ad)

**Comment by jianganghuang** [comment]
Your issue might be related to the code in the "eval_json" function under "ultralytics/models/yolo/detect/val.py". You can  
 check if the file path and environment is correct. And verify whether "self.is_coco" is set to True.

**Comment by DL-Mao** [comment]
@jianganghuang Thank you very much! I have solved the issue. It was likely caused by changing the path of the annotations file, which made it impossible for _pycocotools_ to find the specific JSON path.
