### ISSUE TITLE
predict.py报错

### ISSUE THREAD

**Issue by wyz58** [iMoonLab/Hyper-YOLO#4]
![3ba99e1707a036f34e91846a4f1adbf](https://github.com/user-attachments/assets/38f3141c-5fe9-441f-9fec-4764cf1f7259)
运行train没问题，运行predict报图中错请问怎么解决。

**Comment by jianganghuang** [comment]
感谢您的关注，对于该问题，可能是环境版本不正确导致的，最简单的解决方式是注释该行，直接令fp16=True 或 False。如果需要彻底解决该问题，您需要debug是哪个变量为str类型。
