### ISSUE TITLE
onnxruntime error

### ISSUE THREAD

**Issue by gmx1992** [iMoonLab/Hyper-YOLO#5]
你好作者，我使用了您的模型训练了自己的数据集，在使用onnxruntime-gpu进行推理时报错：`[E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running Sub node. Name:'/model.16/Sub' Status Message: 
/onnxruntime_src/onnxruntime/core/providers/cuda/shared_inc/fast_divmod.h:50 onnxruntime::cuda::DivMod<int>::DivMod(int) d_ >= 1 && d_ <= static_cast<uint32_t>(std::numeric_limits<int>::max()) was false.` 
错误表明：这是由 CUDA 设备上的整数除法运算问题引起的。具体来说，问题出在 fast_divmod.h 文件的 DivMod<int>::DivMod(int) 函数中，它在处理除法时遇到无效的除数（即除数 d_ 不在合理的范围内，或小于 1），从而引发异常（内存爆出等）。 
我可视化graph同时查看源码发现，在超图计算模块时（源码位置：ultralytics/nn/modules/block.py ...distance = torch.cdist(feature, feature)）用到了torch.cdist，而onnx将该算子拆分为Sub、ReduceSum、Pow等算子，最终在Sub算子处报错。   目前我的CUDA版本11.7，ort-gpu版本是1.17，尝试将ort-gpu升级到1.19时，结果推理不报错，但是推理时间延长。
想请教，您的onnxruntime-gpu如何推理成功的。

**Comment by jianganghuang** [comment]
感谢您的关注，正如论文中所提到的，torch.cdist在转onnx部署时会遇到问题，对于此问题，我们建议您使用自定义函数来实现torch.cdist。以下我们提供了一个函数可以替代torch.cdist计算过程“

![image](https://github.com/user-attachments/assets/b7bb908c-c34a-4e5e-9a9b-5ad7892a7b0a)

**Comment by gmx1992** [comment]
> 感谢您的关注，正如论文中所提到的，torch.cdist在转onnx部署时会遇到问题，对于此问题，我们建议您使用自定义函数来实现torch.cdist。以下我们提供了一个函数可以替代torch.cdist计算过程“
> 
> ![image](https://private-user-images.githubusercontent.com/127812522/371853043-b7bb908c-c34a-4e5e-9a9b-5ad7892a7b0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NTk3MTgsIm5iZiI6MTcyNzY1OTQxOCwicGF0aCI6Ii8xMjc4MTI1MjIvMzcxODUzMDQzLWI3YmI5MDhjLWMzNGEtNGU1ZS05YTliLTVhZDc4OTJhN2IwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQwMTIzMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMGFhNWQ3ZTk5MWNkYTNlZmU0ODdjNmNlOGRiZmE1YWE2YTYzMmI4ZGU3NzkzN2FiZjMyZjA0NjRjNDU4NzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rQSiWUqzWkLe_J-TZVVyCKl2Dd_5lNNUelerOL99fCA)

首先感谢您的回复，我之前也是实现了2个算子，均以超时告终；其次，读论文时漏了最后的附录D ,导致走了一些弯路，再次感谢！

**Comment by gmx1992** [comment]
> 感谢您的关注，正如论文中所提到的，torch.cdist在转onnx部署时会遇到问题，对于此问题，我们建议您使用自定义函数来实现torch.cdist。以下我们提供了一个函数可以替代torch.cdist计算过程“
> 
> ![image](https://private-user-images.githubusercontent.com/127812522/371853043-b7bb908c-c34a-4e5e-9a9b-5ad7892a7b0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NjExMTcsIm5iZiI6MTcyNzY2MDgxNywicGF0aCI6Ii8xMjc4MTI1MjIvMzcxODUzMDQzLWI3YmI5MDhjLWMzNGEtNGU1ZS05YTliLTVhZDc4OTJhN2IwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQwMTQ2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzY4ZWM2ZWU3ZDlhNTFlNjMzOGZmYzZlYzY4YzFmYzk4ODA0ZmY5NTc0ZGM3MWI5OThlNDAzYjY0NmU2M2I3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JKJz11-ncvVsZnHLdV606_6d53c_vzUGSYiMqtsbzEE)

首先感谢您的回复，我之前也是实现了2个算子，均以超时告终；
其次，读论文时漏了最后的附录D ,导致走了一些弯路，再次感谢。
