### ISSUE TITLE
CPU usage is too high

### ISSUE THREAD

**Issue by gmx1992** [iMoonLab/Hyper-YOLO#6]
你好作者，我在训练Hyper-YOLOv8m时，CPU占用过高（是在GPU服务器上，CPU占用经常为2000%+），我将worker设置为0也是占用很高。请问，你们训练时有遇到类似问题吗？

**Comment by jianganghuang** [comment]
感谢您的关注，我们也遇到过类似问题，应该属于正常现象，并不是超图带来的，而是数据处理过程会非常耗CPU，尤其是padding过程
