### ISSUE TITLE
Where is the Hypergraph construction code?

### ISSUE THREAD

**Issue by Millielele** [iMoonLab/Hyper-YOLO#8]
Thanks for your excellent work! However, I could not find the hypergraph construction code, could you please let me know?

**Comment by jianganghuang** [comment]
Thanks for your follow, The relevant code is located at 'ultralytics/nn/modules/block.py', as shown in the figure below.
![image](https://github.com/user-attachments/assets/f09576fa-b0b1-4879-afae-90421dcc1fbb)

**Comment by Bian-jh** [comment]
> Thanks for your follow, The relevant code is located at 'ultralytics/nn/modules/block.py', as shown in the figure below. ![image](https://github.com/user-attachments/assets/f09576fa-b0b1-4879-afae-90421dcc1fbb)

Thanks for your excellent work. In equation 3 in the paper,  where is the position of the trainable parameter θ corresponding to the code？ Moreover, it seems that the parameters that can be trained in the HyperComputeModule are very limited, especially in the HyPConv module. Is this normal?

**Comment by jianganghuang** [comment]
The trainable parameter is the fully connected layer self.fc nn.Linear(c1, c2) in HyPConv. The hypergraph is a structure for capturing higher-order correlations and is not a traditional convolutional module. The differences between it and traditional modules can be referred to in [this](https://github.com/iMoonLab/Hyper-YOLO/issues/12#issuecomment-2582699051)
